export const MAIN = {
  GET_ALWAYS_ON_TOP: 'MAIN/GET_ALWAYS_ON_TOP',
  REQUEST_ALWAYS_ON_TOP: 'MAIN/REQUEST_ALWAYS_ON_TOP',
  SEND_ALWAYS_ON_TOP: 'MAIN/SEND_ALWAYS_ON_TOP',
  REQUEST_MINI_PLAYER_MODE: 'MAIN/REQUEST_MINI_PLAYER_MODE',
  SEND_MINI_PLAYER_MODE: 'MAIN/SEND_MINI_PLAYER_MODE',
  SEND_TRANSPARENT_RATE: 'MAIN/SEND_TRANSPARENT_RATE',
  SEND_PLAY_NEXT: 'MAIN/SEND_PLAY_NEXT',
};
export const RENDERER = {
  SEND_ALWAYS_ON_TOP: 'RENDERER/SEND_ALWAYS_ON_TOP',
  SEND_MINI_PLAYER_MODE: 'RENDERER/SEND_MINI_PLAYER_MODE',
};

export default { MAIN, RENDERER };
