export const MAIN = {
  GET_ALWAYS_ON_TOP: 'MAIN/GET_ALWAYS_ON_TOP',
  REQUEST_ALWAYS_ON_TOP: 'MAIN/REQUEST_ALWAYS_ON_TOP',
  SEND_ALWAYS_ON_TOP: 'MAIN/SEND_ALWAYS_ON_TOP',
  REQUEST_MIN_PLAYER_MODE: 'MAIN/REQUEST_MIN_PLAYER_MODE',
  SEND_MIN_PLAYER_MODE: 'MAIN/SEND_MIN_PLAYER_MODE',
};
export const RENDERER = {
  SEND_ALWAYS_ON_TOP: 'RENDERER/SEND_ALWAYS_ON_TOP',
  SEND_MIN_PLAYER_MODE: 'RENDERER/SEND_MIN_PLAYER_MODE',
};

export default { MAIN, RENDERER };
