export const MAIN = {
  GET_ALWAYS_ON_TOP: 'MAIN/GET_ALWAYS_ON_TOP',
  REQUEST_ALWAYS_ON_TOP: 'MAIN/REQUEST_ALWAYS_ON_TOP',
  SEND_ALWAYS_ON_TOP: 'MAIN/SEND_ALWAYS_ON_TOP'
};
export const RENDERER = {
  SEND_ALWAYS_ON_TOP: 'RENDERER/SEND_ALWAYS_ON_TOP',
};

export default { MAIN, RENDERER };
